# Generated by Django 4.1.3 on 2022-12-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(choices=[('1', 'Little or no exercise'), ('2', '1-3 workouts/week'), ('3', '4-5 workouts/week'), ('4', '6-7 workouts/week')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='dontEat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donteat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('L', 'Loss Wieght'), ('G', 'Gain Muscle'), ('M', 'Maintain Weight')], default='L', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Weight_Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentweight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('targetweight', models.IntegerField()),
            ],
        ),
    ]
