# Generated by Django 4.1.3 on 2022-12-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_personfitness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active',
        ),
        migrations.DeleteModel(
            name='dontEat',
        ),
        migrations.DeleteModel(
            name='FitnessGoal',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Weight_Height',
        ),
        migrations.RenameField(
            model_name='personfitness',
            old_name='a',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='personfitness',
            old_name='donteat',
            new_name='Dont_eat',
        ),
        migrations.RenameField(
            model_name='personfitness',
            old_name='g',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='personfitness',
            old_name='currentweight',
            new_name='current_weight',
        ),
        migrations.RenameField(
            model_name='personfitness',
            old_name='targetweight',
            new_name='target_weight',
        ),
    ]
